# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 523ade48e36dc438e31f3f304d4850b91dc6675f9e72bcd300368aa31cfaafac04e5b05a4547189feb57ba6884e6b50e6306f899fea25a9ed4d281a6d3c1682c

test:
  secret_key_base: 8decb6a426ba46c84286a3c1011d053d59e83730723b0b8a1823885b60563e829624892563a930e8684656b6f5bb96a66b424192833210aaf9c24ec15255a430

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
